services:
  ticket-queue:
    build:
      target: development
    image: ticket-queue-test
    container_name: ticket-queue-test
    command: npm run test
    volumes:
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
