services:
  ticket-queue:
    build: .
    image: ticket-queue
    container_name: ticket-queue
    environment:
      MONGO_URI: mongodb://mongodb:27017/ticket-queue
      REDIS_URI: redis://redis:6379
      SESSION_PASSWORD: ${SESSION_PASSWORD:-this-secret-needs-to-be-at-least-32-characters-long}
