services:
  ticket-queue:
    build:
      target: development
    image: ticket-queue-development
    container_name: ticket-queue-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    networks:
      - ticket-queue

networks:
  ticket-queue:
    driver: bridge
    name: ticket-queue
